package io.github.ronniebsimian.huey.client;

import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;

/**
 * GENERATED by tools/gen_model.py - do not edit by hand.
 * Edit the Python script and re-run it instead.
 */
public final class HueyModelGeometry {
	private HueyModelGeometry() {
	}

	public static LayerDefinition create() {
		MeshDefinition mesh = new MeshDefinition();
		PartDefinition root = mesh.getRoot();
		root.addOrReplaceChild("body", CubeListBuilder.create()
			.texOffs(380, 0).addBox(13F, -2F, -34F, 3F, 2F, 58F)
			.texOffs(422, 189).addBox(13F, -4F, -38F, 3F, 2F, 4F)
			.texOffs(0, 189).addBox(12F, -10F, -26F, 2F, 8F, 2F)
			.texOffs(8, 189).addBox(12F, -10F, 12F, 2F, 8F, 2F)
			.texOffs(436, 189).addBox(16F, -3F, -8F, 1F, 2F, 4F)
			.texOffs(0, 71).addBox(-16F, -2F, -34F, 3F, 2F, 58F)
			.texOffs(446, 189).addBox(-16F, -4F, -38F, 3F, 2F, 4F)
			.texOffs(16, 189).addBox(-14F, -10F, -26F, 2F, 8F, 2F)
			.texOffs(24, 189).addBox(-14F, -10F, 12F, 2F, 8F, 2F)
			.texOffs(460, 189).addBox(-17F, -3F, -8F, 1F, 2F, 4F)
			.texOffs(0, 0).addBox(-16F, -12F, -40F, 32F, 3F, 68F)
			.texOffs(200, 0).addBox(-16F, -46F, -30F, 32F, 3F, 58F)
			.texOffs(186, 170).addBox(-15F, -46F, -42F, 30F, 2F, 12F)
			.texOffs(220, 131).addBox(-16F, -43F, 26F, 32F, 31F, 2F)
			.texOffs(288, 131).addBox(15F, -43F, 24F, 1F, 31F, 2F)
			.texOffs(294, 131).addBox(15F, -43F, -16F, 1F, 31F, 2F)
			.texOffs(46, 131).addBox(15F, -26F, -40F, 1F, 14F, 24F)
			.texOffs(442, 71).addBox(15F, -43F, -38F, 1F, 17F, 22F)
			.texOffs(472, 131).addBox(15F, -43F, -40F, 1F, 17F, 2F)
			.texOffs(300, 131).addBox(-16F, -43F, 24F, 1F, 31F, 2F)
			.texOffs(306, 131).addBox(-16F, -43F, -16F, 1F, 31F, 2F)
			.texOffs(96, 131).addBox(-16F, -26F, -40F, 1F, 14F, 24F)
			.texOffs(0, 131).addBox(-16F, -43F, -38F, 1F, 17F, 22F)
			.texOffs(478, 131).addBox(-16F, -43F, -40F, 1F, 17F, 2F)
			.texOffs(390, 131).addBox(-15F, -26F, -46F, 30F, 14F, 6F)
			.texOffs(298, 170).addBox(-12F, -24F, -49F, 24F, 10F, 3F)
			.texOffs(470, 189).addBox(-10F, -20F, -50F, 20F, 5F, 1F)
			.texOffs(0, 170).addBox(-13F, -43F, -42F, 26F, 17F, 2F)
			.texOffs(462, 131).addBox(-1F, -43F, -43F, 2F, 17F, 3F)
			.texOffs(340, 189).addBox(-12F, -30F, -40F, 24F, 4F, 3F)
			.texOffs(232, 189).addBox(4F, -14F, -47F, 8F, 2F, 6F)
			.texOffs(260, 189).addBox(-12F, -14F, -47F, 8F, 2F, 6F)
			.texOffs(352, 170).addBox(4F, -17F, -30F, 8F, 5F, 8F)
			.texOffs(82, 170).addBox(4F, -33F, -22F, 8F, 16F, 2F)
			.texOffs(384, 170).addBox(-12F, -17F, -30F, 8F, 5F, 8F)
			.texOffs(102, 170).addBox(-12F, -33F, -22F, 8F, 16F, 2F)
			.texOffs(464, 170).addBox(-9F, -17F, 12F, 18F, 5F, 6F)
			.texOffs(122, 170).addBox(-9F, -30F, 24F, 18F, 13F, 2F)
			.texOffs(32, 189).addBox(9F, -16F, 17F, 5F, 4F, 6F)
			.texOffs(162, 170).addBox(16.5F, -26F, 19.5F, 1F, 14F, 1F)
			.texOffs(54, 189).addBox(-14F, -16F, 17F, 5F, 4F, 6F)
			.texOffs(166, 170).addBox(-17.5F, -26F, 19.5F, 1F, 14F, 1F)
			.texOffs(122, 71).addBox(-11F, -56F, -14F, 22F, 10F, 48F)
			.texOffs(288, 189).addBox(-9F, -54F, -16F, 18F, 6F, 2F)
			.texOffs(270, 170).addBox(-4F, -54F, 34F, 8F, 8F, 6F)
			.texOffs(188, 189).addBox(-1.5F, -62F, 0F, 3F, 6F, 3F)
			.texOffs(366, 71).addBox(-7F, -44F, 28F, 14F, 16F, 24F)
			.texOffs(262, 71).addBox(-5F, -43F, 52F, 10F, 12F, 42F)
			.texOffs(312, 131).addBox(-3.5F, -42F, 94F, 7F, 9F, 18F)
			.texOffs(76, 189).addBox(-14F, -38F, 78F, 28F, 2F, 8F)
			.texOffs(200, 189).addBox(-0.5F, -33F, 110F, 1F, 6F, 3F)
			.texOffs(362, 131).addBox(-1F, -54F, 104F, 2F, 12F, 12F)
			.texOffs(56, 170).addBox(-1F, -62F, 108F, 2F, 8F, 11F)
			.texOffs(328, 189).addBox(1F, -50F, 111F, 1.5F, 4F, 4F)
			, PartPose.offset(0F, 0F, 0F));
		root.addOrReplaceChild("main_rotor", CubeListBuilder.create()
			.texOffs(208, 189).addBox(-3F, -3F, -3F, 6F, 3F, 6F)
			.texOffs(0, 199).addBox(3F, -2F, -2.5F, 73F, 1F, 5F)
			.texOffs(156, 199).addBox(76F, -2F, -2.5F, 6F, 1F, 5F)
			.texOffs(178, 199).addBox(-76F, -2F, -2.5F, 73F, 1F, 5F)
			.texOffs(334, 199).addBox(-82F, -2F, -2.5F, 6F, 1F, 5F)
			.texOffs(146, 131).addBox(-0.5F, -4F, -18F, 1F, 1F, 36F)
			.texOffs(390, 199).addBox(-1F, -4.5F, 18F, 2F, 2F, 3F)
			.texOffs(400, 199).addBox(-1F, -4.5F, -21F, 2F, 2F, 3F)
			, PartPose.offset(0F, -62F, 1.5F));
		root.addOrReplaceChild("tail_rotor", CubeListBuilder.create()
			.texOffs(356, 199).addBox(-0.5F, -1.5F, -1.5F, 2F, 3F, 3F)
			.texOffs(170, 170).addBox(0F, 1.5F, -1.5F, 0.8F, 11.5F, 3F)
			.texOffs(410, 199).addBox(0F, 13F, -1.5F, 0.8F, 2F, 3F)
			.texOffs(178, 170).addBox(0F, -13F, -1.5F, 0.8F, 11.5F, 3F)
			.texOffs(418, 199).addBox(0F, -15F, -1.5F, 0.8F, 2F, 3F)
			, PartPose.offset(3F, -48F, 113F));
		root.addOrReplaceChild("gun_left", CubeListBuilder.create()
			.texOffs(366, 199).addBox(-1F, -1F, 0F, 2F, 2F, 4F)
			.texOffs(416, 170).addBox(-1F, -1.5F, -10F, 2F, 2.5F, 10F)
			.texOffs(148, 189).addBox(-0.5F, -0.5F, -19F, 1F, 1F, 9F)
			.texOffs(394, 189).addBox(-1.5F, 1F, -6F, 3F, 3F, 4F)
			.texOffs(426, 199).addBox(-0.25F, -1.5F, -18F, 0.5F, 1F, 1F)
			, PartPose.offsetAndRotation(17F, -27F, 20F, 0F, -1.571F, 0F));
		root.addOrReplaceChild("gun_right", CubeListBuilder.create()
			.texOffs(378, 199).addBox(-1F, -1F, 0F, 2F, 2F, 4F)
			.texOffs(440, 170).addBox(-1F, -1.5F, -10F, 2F, 2.5F, 10F)
			.texOffs(168, 189).addBox(-0.5F, -0.5F, -19F, 1F, 1F, 9F)
			.texOffs(408, 189).addBox(-1.5F, 1F, -6F, 3F, 3F, 4F)
			.texOffs(430, 199).addBox(-0.25F, -1.5F, -18F, 0.5F, 1F, 1F)
			, PartPose.offsetAndRotation(-17F, -27F, 20F, 0F, 1.571F, 0F));
		return LayerDefinition.create(mesh, 512, 256);
	}
}
