package io.github.ronniebsimian.huey.client;

import io.github.ronniebsimian.huey.HueyMod;
import net.minecraft.client.model.EntityModel;
import net.minecraft.client.model.geom.ModelLayerLocation;
import net.minecraft.client.model.geom.ModelPart;
import net.minecraft.util.Mth;

/** Geometry lives in HueyModelGeometry (generated by tools/gen_model.py); this class animates it. */
public class HueyModel extends EntityModel<HueyRenderState> {
	public static final ModelLayerLocation LAYER = new ModelLayerLocation(HueyMod.id("huey"), "main");

	private final ModelPart mainRotor;
	private final ModelPart tailRotor;
	private final ModelPart gunLeft;
	private final ModelPart gunRight;

	public HueyModel(ModelPart root) {
		super(root);
		this.mainRotor = root.getChild("main_rotor");
		this.tailRotor = root.getChild("tail_rotor");
		this.gunLeft = root.getChild("gun_left");
		this.gunRight = root.getChild("gun_right");
	}

	@Override
	public void setupAnim(HueyRenderState state) {
		super.setupAnim(state);
		this.mainRotor.yRot = state.rotorAngle * Mth.DEG_TO_RAD;
		this.tailRotor.xRot = state.rotorAngle * 2.6F * Mth.DEG_TO_RAD;
		// guns rest pointing out of their doors (set in the model); swing them to follow the gunner
		this.gunLeft.yRot += state.gunLeftYaw * Mth.DEG_TO_RAD;
		this.gunLeft.xRot += state.gunLeftPitch * Mth.DEG_TO_RAD;
		this.gunRight.yRot += state.gunRightYaw * Mth.DEG_TO_RAD;
		this.gunRight.xRot += state.gunRightPitch * Mth.DEG_TO_RAD;
	}
}
